name: Pytone CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpulse-mainloop-glib0 \
          libpulse0 \
          libglib2.0-0 \
          libqt5multimedia5-plugins \
          xvfb \
          libxcb-xinerama0 \
          libxkbcommon-x11-0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint pytone.py
      run: |
        flake8 pytone.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 pytone.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run pytone.py headless
      run: xvfb-run -a python pytone.py

    - name: Run pytest
      run: pytest || echo "No tests found, skipping"



